---
- name: Create Host Install inventory
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get Host IP Address
      ansible.builtin.setup:
        gather_subset:
          - default_ipv4

    - name: Create inventory directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0750'
      loop:
        - "{{ playbook_dir }}/inventory"
        - "{{ playbook_dir }}/inventory/host_vars"
        - "{{ playbook_dir }}/inventory/host_vars/{{ skupper_host }}"

    - name: "Create {{ skupper_host }} services variable file"
      ansible.builtin.copy:
        src: files/customer_services.yml
        dest: "{{ playbook_dir }}/inventory/host_vars/{{ skupper_host }}/services.yml"
        mode: '0640'

    - name: "Create {{ skupper_host }} inventory file"
      ansible.builtin.template:
        src: templates/install_host.yml.j2
        dest: "{{ playbook_dir }}/inventory/{{ skupper_host }}.yml"
        mode: '0640'
